# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/visage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/visage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12proto/visage.proto\"\x18\n\x06\x43oords\x12\x0e\n\x06values\x18\x01 \x03(\x02\"[\n\x0c\x43\x65llMetadata\x12\x0b\n\x03\x61ge\x18\x05 \x01(\t\x12\x0e\n\x06tissue\x18\x06 \x01(\t\x12\x11\n\tsubtissue\x18\x07 \x01(\t\x12\x1b\n\x13\x63\x65ll_ontology_class\x18\x08 \x01(\t\"-\n\rCellsMetadata\x12\x1c\n\x05\x63\x65lls\x18\x01 \x03(\x0b\x32\r.CellMetadatab\x06proto3'
)




_COORDS = _descriptor.Descriptor(
  name='Coords',
  full_name='Coords',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='Coords.values', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=46,
)


_CELLMETADATA = _descriptor.Descriptor(
  name='CellMetadata',
  full_name='CellMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='age', full_name='CellMetadata.age', index=0,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tissue', full_name='CellMetadata.tissue', index=1,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subtissue', full_name='CellMetadata.subtissue', index=2,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cell_ontology_class', full_name='CellMetadata.cell_ontology_class', index=3,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=139,
)


_CELLSMETADATA = _descriptor.Descriptor(
  name='CellsMetadata',
  full_name='CellsMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cells', full_name='CellsMetadata.cells', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=186,
)

_CELLSMETADATA.fields_by_name['cells'].message_type = _CELLMETADATA
DESCRIPTOR.message_types_by_name['Coords'] = _COORDS
DESCRIPTOR.message_types_by_name['CellMetadata'] = _CELLMETADATA
DESCRIPTOR.message_types_by_name['CellsMetadata'] = _CELLSMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Coords = _reflection.GeneratedProtocolMessageType('Coords', (_message.Message,), {
  'DESCRIPTOR' : _COORDS,
  '__module__' : 'proto.visage_pb2'
  # @@protoc_insertion_point(class_scope:Coords)
  })
_sym_db.RegisterMessage(Coords)

CellMetadata = _reflection.GeneratedProtocolMessageType('CellMetadata', (_message.Message,), {
  'DESCRIPTOR' : _CELLMETADATA,
  '__module__' : 'proto.visage_pb2'
  # @@protoc_insertion_point(class_scope:CellMetadata)
  })
_sym_db.RegisterMessage(CellMetadata)

CellsMetadata = _reflection.GeneratedProtocolMessageType('CellsMetadata', (_message.Message,), {
  'DESCRIPTOR' : _CELLSMETADATA,
  '__module__' : 'proto.visage_pb2'
  # @@protoc_insertion_point(class_scope:CellsMetadata)
  })
_sym_db.RegisterMessage(CellsMetadata)


# @@protoc_insertion_point(module_scope)
